### ISSUE TITLE
FEATURE REQUEST - Add instance property "observedProgress" same UIProgressView

### ISSUE THREAD

**Issue by CPiersigilli** [derekcoder/SwiftProgressView#1]
I'd like you to insert instance property `observedProgress` to your `SwiftProgressView`: is it possible to do this?
Best regards.
Cesare Piersigilli

**Comment by derekcoder** [comment]
Hi @CPiersigilli,

In `ProgressView` class, there is already an instance property called `progress`. Could you please tell me why you need another instance property `observedProgress `?

**Comment by derekcoder** [comment]
Hi @CPiersigilli,

Thank you for your suggestion. I already added `observedProgress ` to `ProgressView` in [Tag 1.3.0](https://github.com/derekcoder/SwiftProgressView/releases/tag/1.3.0). Please have a try and welcome to feedback if you have any questions.

I will close this issue firstly. If you have any other related questions, feel free to open another issue.

**Comment by CPiersigilli** [comment]
Great job. For me now works fine.
